# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
# Uncomment this line if you're using Swift
# use_frameworks!

use_frameworks!

target 'new_swift' do
	pod 'RealmSwift', '>= 0.95.2'
end

