# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'realm' do
	pod 'RealmSwift', '>= 0.95.2'
end

target 'realmTests' do

end

target 'realmUITests' do

end

